[package]
name = "rules-rs"
version = "0.1.0"
authors = ["Paolo D'Incau <>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
thiserror = "1.0.24"
chrono = "0.4"
